### PR TITLE
add client credential grant type to the indexer

### PR DESCRIPTION
**Pull request by jeremy-seipelt**
#19

### CODE REVIEW

**Review by mkucmus — APPROVED** [review]
thanks for that!

**Comment by mo-mueller** [comment]
Did you even test it? I'm getting this error right now: 

`ReferenceError: grant_type is not defined`

You missed "grant_type" on the const object in line 2.

**Comment by mkucmus** [comment]
I just added it as a destructured parameter

**Comment by mo-mueller** [comment]
Now there is a typo in your parameter: grand_type != grant_type

On top of that client_id and client_secret are also missing.

**Pull request merged**
